-- AlterTable
ALTER TABLE "sponsors" ADD COLUMN IF NOT EXISTS "tier" TEXT NOT NULL DEFAULT '';
ALTER TABLE "sponsors" ADD COLUMN IF NOT EXISTS "website" TEXT NOT NULL DEFAULT '';
ALTER TABLE "sponsors" ADD COLUMN IF NOT EXISTS "address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "sponsors" ADD COLUMN IF NOT EXISTS "contactName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "sponsors" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT NOT NULL DEFAULT '';
